name: Report a bug
description: Tell us about a bug or issue you may have identified in Open {re}Source.
title: 'Provide a general summary of the issue'
labels: [bug]
assignees: '-'
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/Open-reSource/openresource.dev/issues?q=is%3Aissue) for duplicate or closed issues
          required: true
        - label: I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/CONTRIBUTING.md)
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce and screenshots if necessary.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
        - All
        - N/A
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
        - All
        - N/A
